#!/bin/bash

printf "Project Name: "
read projectName
printf "Group ID: "
read groupid
mvn archetype:generate -DgroupId="$groupid" -DartifactId="$projectName" -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5 -DinteractiveMode=false
